#!/bin/bash
echo Backing up /public/uploads directory.
mkdir ~/bkupMedia
mkdir ~/bkupMedia/userdata
cp -r ../myCMS/public/uploads/* ~/bkupMedia/

echo Backing up user data
mkdir ~/bkupMedia/userdata
cp -r ../myCMS/private/userdata ~/bkupMedia/userdata/private
cp -r ../myCMS/public/uploads/geologs ~/bkupMedia/userdata/public

echo Removing old myCMS directory...
rm -rf ../myCMS/

echo Copying Keystone v0.4 files...
cp -r ../keystone4/ ../myCMS
echo Keystone v0.4 Copied to myCMS

echo Copying ConnextCMS files...
cd ~/connextCMS
./merge-connextcms-keystone
cd ~/rpiovn