#!/bin/bash
echo Preparing to copy RPiOVN files...

echo Copying Keystone core files...
cp keystone.js ../myCMS/

echo Copying Keystone templates...
cp templates/views/*.hbs ../myCMS/templates/views/
cp templates/views/layouts/*.hbs ../myCMS/templates/views/layouts/

echo Copying Keystone models...
cp models/*.js ../myCMS/models/

echo Copying Keystone routes...
cp routes/index.js ../myCMS/routes/
cp routes/api/*.js ../myCMS/routes/api/
cp routes/views/*.js ../myCMS/routes/views/

echo Copying public files...
cp public/favicon.ico ../myCMS/public
cp public/images/* ../myCMS/public/images/
cp public/js/app/main_dashboard_app.js ../myCMS/public/js/app/

echo Copying Backbone models, views, and templates
cp public/js/app/model/*.js ../myCMS/public/js/app/model/
cp public/js/app/views/*.js ../myCMS/public/js/app/views/
cp public/js/app/templates/*.html ../myCMS/public/js/app/templates/

echo Copying library files...
cp public/js/lib/*.js ../myCMS/public/js/lib/
