#!/bin/bash
echo Preparing to copy RPiOVN files...

echo Copying Keystone core files...
cp keystone.js ../myCMS/

echo Copying Keystone templates...
cp templates/views/*.hbs ../myCMS/templates/views/
cp templates/views/layouts/*.hbs ../myCMS/templates/views/layouts/

echo Copying public files
cp public/favicon.ico ../myCMS/public
cp public/images/* ../myCMS/public/images/
cp public/js/app/main_dashboard_app.js ../myCMS/public/js/app/

